apiVersion: v1
kind: Service
metadata:
  name: netflix
  namespace: netflix
spec:
  selector:
    app: netflix
  type: NodePort
  ports:
    - protocol: TCP
      port: 9999
      targetPort: 9999
      nodePort: 30007
  