apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-app
  namespace: netflix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix
  template:
    metadata:
      labels:
        app: netflix
    spec:
      containers:
        - name: netflix-clone
          image: soufiane01/netflix-clone:v7
          ports:
            - containerPort: 9999
