name: Deploy to Azure VM

on:
  push:
    branches:
      - main  # Triggers deployment on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.VM_SSH_KEY }}

    - name: Copy files to Azure VM
      run: |
        scp -o StrictHostKeyChecking=no -r . ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }}:/home/${{ secrets.VM_USERNAME }}/app

    - name: Build and run Docker container on Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USERNAME }}@${{ secrets.VM_IP }} << EOF
          cd /home/${{ secrets.VM_USERNAME }}/app
          docker build --build-arg TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }} -t netflix-clone .
          docker stop netflix-clone || true  # Stop any existing container
          docker rm netflix-clone || true    # Remove old container if exists
          docker run -d -p 8081:80 --name netflix-clone netflix-clone
        EOF
