trigger:
  branches:
    include:
      - main  # Trigger the pipeline when changes are pushed to the 'main' branch

pool:
  vmImage: 'ubuntu-latest'  # This is the environment where the pipeline will run (Ubuntu-based VM)

variables:
  dockerImageName: 'netflix-clone'  # Docker image name
  tmdbApiKey: '$(TMDB_V3_API_KEY)'  # TMDB API key as a secret

jobs:
- job: BuildAndDeploy
  displayName: 'Build and Deploy Netflix Clone'
  steps:
  - task: Checkout@2
    displayName: 'Checkout code'

  # Build Docker Image
  - script: |
      echo "Building the Docker image..."
      docker build --build-arg TMDB_V3_API_KEY=$(tmdbApiKey) -t $(dockerImageName) .
    displayName: 'Build Docker Image'

  # SSH to Azure VM and set up secrets in Key Vault
  - script: |
      echo "SSH into Azure VM and set secret in KeyVault..."
      ssh -i "$(SSH_PRIVATE_KEY_PATH)" azureuser@40.118.226.249 <<EOF
        cd moviesstreamg2
        az keyvault secret set --vault-name key --name "TMDB_API_KEY" --value "$(tmdbApiKey)"
      EOF
    displayName: 'Set TMDB API Key in KeyVault'
    env:
      SSH_PRIVATE_KEY_PATH: $(SSH_PRIVATE_KEY_PATH)  # Ensure this is a secret variable in the pipeline

  # Run the Docker container
  - script: |
      echo "Running Docker container..."
      docker run -d -p 8081:80 $(dockerImageName)
    displayName: 'Run Docker container'
