name: Deploy to Azure VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up SSH agent
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      # Deploy the app
      - name: SSH to the server and run docker commands
        run: |
          ssh -vvv -o StrictHostKeyChecking=no azureuser@${{ secrets.VM_IP }} << 'EOF'
            docker build --build-arg TMDB_V3_API_KEY=${{ secrets.TMDB_API_KEY }} -t netflix-clone .
            docker run -d -p 8081:80 netflix-clone
          EOF
